language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  email:
    recipients:
      - j.sheerp@gmail.com
      - javier.molina.maldonado@alumnos.upm.es
      
script: mvn verify